// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_zMKCQujXqhvydLkh_ecqaF9XI-Fp8UA',
    appId: '1:244296007741:web:e5444a12d1752ecb3cea54',
    messagingSenderId: '244296007741',
    projectId: 'mountmeru-amp-mobile',
    authDomain: 'mountmeru-amp-mobile.firebaseapp.com',
    storageBucket: 'mountmeru-amp-mobile.appspot.com',
    measurementId: 'G-LF853QW47G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANKjyCjX_JvlOdQoZtqOIfswJyd7IMzXI',
    appId: '1:244296007741:android:55f106b0763107143cea54',
    messagingSenderId: '244296007741',
    projectId: 'mountmeru-amp-mobile',
    storageBucket: 'mountmeru-amp-mobile.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlS0FV4G82OFZ4-WgU-rIF_SGA2LQSWsA',
    appId: '1:244296007741:ios:5922052a3e61fef73cea54',
    messagingSenderId: '244296007741',
    projectId: 'mountmeru-amp-mobile',
    storageBucket: 'mountmeru-amp-mobile.appspot.com',
    iosBundleId: 'com.mountmeru.auditmanagementplatform.amp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlS0FV4G82OFZ4-WgU-rIF_SGA2LQSWsA',
    appId: '1:244296007741:ios:5922052a3e61fef73cea54',
    messagingSenderId: '244296007741',
    projectId: 'mountmeru-amp-mobile',
    storageBucket: 'mountmeru-amp-mobile.appspot.com',
    iosBundleId: 'com.mountmeru.auditmanagementplatform.amp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_zMKCQujXqhvydLkh_ecqaF9XI-Fp8UA',
    appId: '1:244296007741:web:a3c1eca39847fd9e3cea54',
    messagingSenderId: '244296007741',
    projectId: 'mountmeru-amp-mobile',
    authDomain: 'mountmeru-amp-mobile.firebaseapp.com',
    storageBucket: 'mountmeru-amp-mobile.appspot.com',
    measurementId: 'G-R4Y0VE5ZW6',
  );
}
